export interface PublicAiLessonSnapshot {
  sourcePath: `/ai/lessons/${string}`;
  heading: string;
  summary: string;
  youtubeId: string;
  notes: string[];
}

// Public lesson bodies captured from the rendered Fanout pages on 2026-08-24.
// Topics absent from this list are overview-only Pro topics on the source site.
export const publicAiLessonSnapshots: PublicAiLessonSnapshot[] = [
  {
    sourcePath: '/ai/lessons/math-fundamentals-functions',
    heading: 'Functions',
    summary: 'A complete free lesson on Functions, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'kvGsIo1TmsM',
    notes: [
      'Functions are the foundation of neural networks. A function is a mathematical relationship that maps inputs to outputs.',
      'Linear Function: f(x) = 2x + 3 — takes any number x and returns 2x + 3.',
      'Quadratic Function: f(x) = x² + 2x + 1',
      'Mathematical Definition: A function f: A → B maps every element in set A to exactly one element in set B.',
      'Types of Functions:',
      'Linear Functions — f(x) = mx + b (slope m, y-intercept b)',
      'Polynomial Functions — f(x) = aₙxⁿ + ... + a₁x + a₀',
      'Exponential Functions — f(x) = aˣ',
      'Trigonometric Functions — used in RoPE (Rotary Positional Embeddings)',
      'Neural Network Functions:',
      'Sigmoid — f(x) = 1 / (1 + e^(-x)), squashes to (0,1)',
      'ReLU — f(x) = max(0, x), the most popular activation',
      'Tanh — f(x) = (eˣ - e⁻ˣ) / (eˣ + e⁻ˣ), squashes to (-1,1)',
    ],
  },
  {
    sourcePath: '/ai/lessons/math-fundamentals-derivatives',
    heading: 'Derivatives',
    summary: 'A complete free lesson on Derivatives, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: '9vKqVkMQHKk',
    notes: [
      'Derivatives tell you how fast a function is changing at any point.',
      'Common Derivative Rules:',
      'Power Rule: d/dx[xⁿ] = nxⁿ⁻¹',
      "Constant Multiple: d/dx[cf(x)] = c·f'(x)",
      "Sum Rule: d/dx[f(x) + g(x)] = f'(x) + g'(x)",
      "Product Rule: d/dx[f(x)·g(x)] = f'(x)·g(x) + f(x)·g'(x)",
      "Chain Rule: d/dx[f(g(x))] = f'(g(x))·g'(x)",
      'Partial Derivatives: When a function has multiple inputs (like neural network weights), we take the derivative with respect to one variable while holding others constant.',
      'Key for neural networks: derivatives power backpropagation.',
    ],
  },
  {
    sourcePath: '/ai/lessons/math-fundamentals-vectors',
    heading: 'Vectors',
    summary: 'A complete free lesson on Vectors, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'fNk_zzaMoSs',
    notes: [
      'Vectors are ordered lists of numbers representing magnitude and direction.',
      'Key Operations:',
      'Addition: [a₁, a₂] + [b₁, b₂] = [a₁+b₁, a₂+b₂]',
      'Scalar Multiplication: c·[a₁, a₂] = [ca₁, ca₂]',
      'Dot Product: a·b = a₁b₁ + a₂b₂ (measures similarity)',
      'Magnitude: ||v|| = √(v₁² + v₂² + ...)',
      'In neural networks, inputs, weights, and embeddings are all vectors. In LLMs, word embeddings are high-dimensional vectors where similar words have similar vectors.',
    ],
  },
  {
    sourcePath: '/ai/lessons/math-fundamentals-gradients',
    heading: 'Gradients',
    summary: 'A complete free lesson on Gradients, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'vp2oUoBDH4w',
    notes: [
      "The gradient generalizes derivatives to multiple dimensions. It's a vector pointing in the direction of steepest increase.",
      'What the Gradient Tells Us:',
      'Direction: Which way to go to increase the function fastest',
      'Magnitude: How steep the slope is',
      'Gradient Descent: The core of machine learning training. We move in the opposite direction of the gradient to minimize the loss function. The gradient tells us exactly how to update each weight to reduce error.',
    ],
  },
  {
    sourcePath: '/ai/lessons/math-fundamentals-matrices',
    heading: 'Matrices',
    summary: 'A complete free lesson on Matrices, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: '5H4crNlLK_A',
    notes: [
      'A matrix is a 2D array of numbers. Neural networks are essentially chains of matrix operations.',
      'Key Operations:',
      'Addition/Subtraction — element-wise, same shapes required',
      'Scalar Multiplication — multiply every element',
      'Matrix Multiplication — (m×n) @ (n×p) = (m×p), inner dimensions must match',
      'Transpose — flip rows and columns, Aᵀ',
      'Determinant — scalar value, det(A) = 0 means non-invertible',
      'Inverse — A⁻¹ such that A·A⁻¹ = I',
      'Special Matrices: Identity (I), Diagonal, Symmetric, Orthogonal.',
    ],
  },
  {
    sourcePath: '/ai/lessons/math-fundamentals-hadamard-product',
    heading: 'Hadamard Product (Element-wise Op)',
    summary: 'A complete free lesson on Hadamard Product (Element-wise Op), with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: '_MaVzNUjMPk',
    notes: [
      'The Hadamard Product is simply element-wise multiplication.',
      'Why it\'s the "King" of Efficiency: Element-wise operations are much faster than matrix multiplication. The Jacobian of an element-wise operation is diagonal, making backprop through it very efficient.',
      'In Python: Use * for element-wise, @ for matrix multiplication.',
    ],
  },
  {
    sourcePath: '/ai/lessons/math-fundamentals-moving-averages',
    heading: 'Moving Averages (EMA)',
    summary: 'A complete free lesson on Moving Averages (EMA), with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'lAq96T8FkTw',
    notes: [
      'Dealing with noise in training signals.',
      'Simple Moving Average (SMA): Average of last N values. Problem: requires storing N values.',
      'Exponential Moving Average (EMA): v_t = β·v_{t-1} + (1-β)·x_t — recursive, memory-efficient.',
      'Why This Matters for Adam Optimizer:',
      'Momentum = EMA of Gradients (first moment)',
      'RMSProp = EMA of Squared Gradients (second moment)',
      'Adam combines both for adaptive learning rates per parameter.',
    ],
  },
  {
    sourcePath: '/ai/lessons/pytorch-fundamentals-7-pytorch-tasks',
    heading: '7 PyTorch Tasks (Advanced)',
    summary: 'A complete free lesson on 7 PyTorch Tasks (Advanced), with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'QtlDV2r1ryE',
    notes: ['Advanced PyTorch challenges to test and solidify your understanding of tensor operations.'],
  },
  {
    sourcePath: '/ai/lessons/reinforcement-learning-ppo-llm-reasoning',
    heading: 'PPO, LLM Reasoning, Importance Ratio, Advantage',
    summary: 'A complete free lesson on PPO, LLM Reasoning, Importance Ratio, Advantage, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'TjHH_--7l8g',
    notes: ['Proximal Policy Optimization — the algorithm behind RLHF for LLMs. Uses importance ratio and clipping to make stable policy updates.'],
  },
  {
    sourcePath: '/ai/lessons/reinforcement-learning-qwen-deepseek-grpo',
    heading: 'Qwen 3 GSPO & DeepSeek GRPO — LLM Reasoning',
    summary: 'A complete free lesson on Qwen 3 GSPO & DeepSeek GRPO — LLM Reasoning, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'L94MdLdP21s',
    notes: ['Modern approaches to improving LLM reasoning through reinforcement learning — Group Relative Policy Optimization and related techniques.'],
  },
  {
    sourcePath: '/ai/lessons/llm-from-scratch-llama-4',
    heading: 'Llama 4 From Scratch',
    summary: 'A complete free lesson on Llama 4 From Scratch, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'yXbF-1n9wxs',
    notes: ["Building Meta's LLaMA 4 architecture from scratch — understanding the design choices behind one of the most influential open-source LLMs."],
  },
  {
    sourcePath: '/ai/lessons/code-write-publish-ai-research-paper',
    heading: 'How do you turn an LLM experiment into a publishable AI research paper?',
    summary: 'Build an LLM, compare Muon and Adam, structure experiments, and turn the evidence into a publishable AI research paper.',
    youtubeId: 'O2yAMJu8LpI',
    notes: [
      'The Complete Pipeline:',
      'Code LLM from scratch',
      'Code experiments (Muon vs Adam optimizer comparison)',
      'Write the paper',
      'Skills Covered:',
      'LLM Architecture: MoE with expert layers, top-k routing, auxiliary loss, RoPE, multi-head attention',
      'Optimization: Implement Muon optimizer, benchmark against Adam',
      'ML Engineering: Structure projects, pipelines, trainers, run cloud experiments',
      'Research: Design experiments, turn results into a publishable paper',
      'Paper: github.com/vukrosic/noptims',
    ],
  },
  {
    sourcePath: '/ai/lessons/ml-pipeline-dvc-aws-s3',
    heading: 'How do you build a reproducible ML pipeline with DVC and AWS S3?',
    summary: 'Build a reproducible spam-detection pipeline with DVC stages, versioned artifacts, and AWS S3 remote storage.',
    youtubeId: 'oYIBwbHM_PI',
    notes: [
      'End-to-end NLP Spam Detection pipeline with MLOps best practices.',
      'Pipeline Stages: Data Ingestion → Data Validation → Pre-processing → Model Training & Evaluation',
      'Key Properties:',
      'Modularity: Each stage is independent — robust and maintainable',
      'Data Versioning: DVC tracks data/model versions with code-level rigor',
      'Cloud Integration: AWS S3 as DVC Remote for heavy datasets and models',
      'Reproducibility: Defined via dvc.yaml for automatic pipeline execution',
      'Infrastructure: IAM User & S3 for secure storage, dvc stage add with dependencies (-d) and outputs (-o).',
    ],
  },
  {
    sourcePath: '/ai/lessons/bonus-lessons-seq-len-vs-batch',
    heading: 'Train LLM — Sequence Length vs Batch Size',
    summary: 'A complete free lesson on Train LLM — Sequence Length vs Batch Size, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'bu5dhaLmr7E',
    notes: [
      'Exploring the trade-offs between batch size and sequence length when training LLMs.',
      'Experiment Setup: Ablation study comparing different batch size × sequence length configurations while keeping total tokens constant.',
      'Key Components:',
      'Experiment configuration with ablation matrix',
      'Hybrid Optimizer (Muon + AdamW)',
      'Mixed-precision training with GradScaler',
      'Gradient accumulation for large effective batch sizes',
    ],
  },
  {
    sourcePath: '/ai/lessons/bonus-lessons-swiglu',
    heading: 'SwiGLU — Better Neural Networks',
    summary: 'A complete free lesson on SwiGLU — Better Neural Networks, with practical notes and a guided video from the Fanout AI research curriculum.',
    youtubeId: 'enPFr-WxHgQ',
    notes: ['SwiGLU activation function — a gated variant of Swish that has become the standard activation in modern LLMs like LLaMA, PaLM, and Mistral. Outperforms ReLU and GELU in practice.'],
  },
  {
    sourcePath: '/ai/lessons/tiny-recursive-model-arc-agi',
    heading: 'How can a 7M-parameter recursive model outperform much larger models on ARC-AGI?',
    summary: 'Understand the nested recursion, adaptive computation, and Q-head behind the 7M-parameter Tiny Recursive Model.',
    youtubeId: 'P9zzUM0PrBM',
    notes: [
      'How a 7M parameter model beats 1T models at Sudoku, Mazes, and ARC-AGI.',
      'TRM Architecture: Uses recursive computation with three nested loops:',
      'Innermost Loop (latent recursion): Phase A (reasoning, updating z) + Phase B (refining answer y)',
      'Middle Loop (deep recursion): 2 warm-up rounds without gradients + 1 final with gradients',
      'Outermost Loop: Up to 16 repetitions with adaptive computation time via learned Q head',
      'The key insight: small models can match or beat massive ones through recursive depth instead of parameter count.',
    ],
  },
];

export const publicAiLessonBySourcePath = new Map(
  publicAiLessonSnapshots.map((snapshot) => [snapshot.sourcePath, snapshot]),
);
